### ISSUE TITLE
Installation problem.

### ISSUE THREAD

**Issue by jubair0614** [tsantalis/jdeodorant-commandline#10]
I was trying to install the standalone version in windows 64-bit machine with eclipse oxygen. 
### problem details
'Export Product' has encountered a problem.
Cannot complete the install because one or more required items could not be found.

Cannot complete the install because one or more required items could not be found.
 Software being installed: JDeodorant-Commandline-Product-Configuration 0.1.0 (JDeodorant-Commandline-Product-Configuration 0.1.0)
 Missing requirement: Eclipse Application Services 2.1.0.v20170407-0928 (org.eclipse.e4.core.services 2.1.0.v20170407-0928) requires 'osgi.extender osgi.component [1.2.0,2.0.0)' but it could not be found
 Cannot satisfy dependency:

**Comment by tsantalis** [comment]
Please follow this [guide](https://github.com/tsantalis/jdeodorant-commandline/blob/print-opportunities/README.md)
