### ISSUE TITLE
Feature envy from JDeodorant

### ISSUE THREAD

**Issue by Ivan-Veselov** [tsantalis/jdeodorant-commandline#13]
README file says "This is an Eclipse plug-in that allows running JDeodorant for identifying refactoring opportunities and applying them in the batch mode". So, I wanted to use this tool to search for move method refactorings opportunities. But it seems that this tool supports only clone detection. How can I search for move method opportunities? If it's not possible then it's better to clarify it in README.

**Comment by tsantalis** [comment]
@Ivan-Veselov Please clone the `print-opportunities` branch, which analyzes all open projects in the specified workspace and prints the detected refactoring opportunities.
The code you are looking for can be found at https://github.com/tsantalis/jdeodorant-commandline/blob/print-opportunities/src/ca/concordia/jdeodorant/eclipse/commandline/Application.java#L230-L235
