### ISSUE TITLE
Plug-in "ca.concordia.jdeodorant.eclipse.commandline-lambda" was unable to instantiate class "ca.concordia.jdeodorant.eclipse.commandline.Application".

### ISSUE THREAD

**Issue by asif33** [tsantalis/jdeodorant-commandline#16]
I followed the official [tutorial](https://github.com/tsantalis/jdeodorant-commandline) on how to launch JDeodorant as a stand alone command line application, and when I run ./eclipse -p projectname -m print_opportunities I get the following error:

Plug-in "ca.concordia.jdeodorant.eclipse.commandline-lambda" was unable to instantiate class "ca.concordia.jdeodorant.eclipse.commandline.Application".

Caused by: java.lang.ClassNotFoundException: gr.uom.java.ast.CompilationErrorDetectedException cannot be found by ca.concordia.jdeodorant.eclipse.commandline-lambda_1.0.0.202008251507

I repeated the whole process using [this](https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities) tutorial still getting the same error.

Do you know what might be the problem?

I am using macOS Catalina and latest version of Eclipse and JDK 14

**Comment by tsantalis** [comment]
duplicate report https://github.com/tsantalis/JDeodorant/issues/79
