### ISSUE TITLE
Missing classes in jDeodorant

### ISSUE THREAD

**Issue by ThisIsIvan** [tsantalis/jdeodorant-commandline#9]
Hi guys,

I've been trying to use your tool on a bachelor thesis I'm currently working on.

As it seems the cmdline tool is using some classes that are not existent in jDeodorant (anymore).

"gr.uom.java.ast.decomposition.cfg.mapping.PDGExpressionGap" and "gr.uom.java.ast.decomposition.cfg.mapping.PDGNodeBlockGap" are missing in "ca.concordia.jdeodorant.eclipse.commandline.cloneinfowriter.CloneInfoCSVWriter".

Do you have any tips on how to fix this?

Cheers
Ivan

**Comment by dmazinanian** [comment]
Hi Ivan,

The `jdeodorant-commandline` project currently works only with the `JLS8-support` branch of JDeodorant. Switching JDeodorant to that branch will solve your problem.

Please let us know if you have further problems.

**Comment by ThisIsIvan** [comment]
Hi dmazinanian,

sry to message you hear. I have another question regarding the cmdline tool.
Am I correct in seeing that it is not possible to parse the actual project with JDeodorant's detection methods with the cmdline tool?
The three modes all require some form of output of another detection tool.

Thanks,
Ivan

**Comment by dmazinanian** [comment]
Hi Ivan,

Which three methods are you talking about? Are you following the `README`?

By *parsing*, you mean detecting code smells and refactoring using JDeodorant? Or you just need to parse the projects and get ASTs?

You can also take this conversation offline. Please check my GitHub profile -> Webpage and find my Email addresses there ;)

**Comment by ThisIsIvan** [comment]
Hi Davood,
I've sent you an email :)
